ulyaoth/repository

- spotify/README
- spotify/build-ulyaoth-spotify.sh
- ulyaoth-banana/README
- ulyaoth-banana/SPECS/ulyaoth-banana.spec
- ulyaoth-banana/build-ulyaoth-banana.sh
- ulyaoth/README
- ulyaoth/SPECS/ulyaoth.spec
- ulyaoth/build-ulyaoth.sh
Updating the build and rpm's to use the new github.
> fixed urls.

- ulyaoth-nginx-modsecurity/SPECS/ulyaoth-nginx-modsecurity.spec
- ulyaoth-nginx-modsecurity/build-ulyaoth-nginx-modsecurity.sh
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi.spec
- ulyaoth-nginx-naxsi/build-ulyaoth-nginx-mainline-naxsi-masterbuild.sh
- ulyaoth-nginx-naxsi/build-ulyaoth-nginx-mainline-naxsi.sh
- ulyaoth-nginx-naxsi/build-ulyaoth-nginx-naxsi.sh
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-mainline-pagespeed.spec
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-pagespeed.spec
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-mainline-pagespeed.sh
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-pagespeed.sh
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger4.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger4.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger4.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger4.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
- ulyaoth-nginx/build-ulyaoth-nginx-mainline.sh
- ulyaoth-nginx/build-ulyaoth-nginx.sh
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
Multiple build fixes and Updating 8.0.27.
> Multiple updates.

- ulyaoth-tomcat-multi/README
- ulyaoth-tomcat-multi/SOURCES/functions
- ulyaoth-tomcat-multi/SOURCES/preamble
- ulyaoth-tomcat-multi/SOURCES/server
- ulyaoth-tomcat-multi/SOURCES/tomcat@.service
- ulyaoth-tomcat-multi/SPECS/ulyaoth-tomcat-multi.spec
- ulyaoth-tomcat-multi/build-ulyaoth-tomcat-multi.sh
> Creating tomcat multi.

- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi.spec
> Symlink for nxapi to /opt/naxsi.

- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi.spec
> Fix mistakes.

- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi-masterbuild.spec
- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-naxsi.spec
> Final changes before release.

- ulyaoth-nginx-naxsi/SPECS/ulyaoth-nginx-mainline-naxsi.spec
> Fixed rpm name.

- ulyaoth-zookeeper/README
- ulyaoth-zookeeper/SOURCES/zookeeper.init
- ulyaoth-zookeeper/SOURCES/zookeeper.service
- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.4.spec
- ulyaoth-zookeeper/build-ulyaoth-zookeeper3.4.sh
> Start on Zookeeper rpms.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
- ulyaoth-kibana/build-ulyaoth-kibana4.sh
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger4.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger4.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
> Update Kibana to 4.3.1.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Fixed sources to auto download.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
- ulyaoth-redis/build-ulyaoth-redis3.sh
> Updated to Redis 3.0.6.

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5-docs.sh
- ulyaoth-solr/build-ulyaoth-solr5-examples.sh
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updated to solr 5.4.0.

- ulyaoth-apr/README
- ulyaoth-apr/SPECS/ulyaoth-apr.spec
- ulyaoth-apr/build-apr.sh
> Start on apr package.

- ulyaoth-apr/SPECS/ulyaoth-apr.spec
> Updated spec file.

- ulyaoth-tomcat-native/README
- ulyaoth-tomcat-native/SPECS/ulyaoth-tomcat-native1.2.spec
- ulyaoth-tomcat-native/build-ulyaoth-tomcat-native1.2.sh
> Creating Tomcat Native 1.2 rpms.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls.spec
- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls2.1.spec
- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls2.2.spec
> Removed / Fixed obsoletes problem :(

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Change + Update to OpenSSL 1.1.0 Alpha 2

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> fixed build dir.

- ulyaoth-tengine/SPECS/ulyaoth-tengine.spec
- ulyaoth-tengine/build-ulyaoth-tengine.sh
#266
- Updated to Tengine 2.1.2.
- Added http/2.
- Added Stream module.
- Added Headers More module.
> Updated to Tengine 2.1.2.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updated to Solr 5.4.1.

- ulyaoth-solr/SPECS/ulyaoth-solr4.spec
- ulyaoth-solr/build-ulyaoth-solr4.sh
> Fix small mistakes.

- ulyaoth-solr/SPECS/ulyaoth-solr4.spec
> removed non used bits.

- ulyaoth-rpm-build.sh
> added solr 4

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
> Updating openssl.

- ulyaoth-go/README
- ulyaoth-go/SPECS/ulyaoth-go.spec
- ulyaoth-go/build-ulyaoth-go.sh
> golang rpm

- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
> Updating to Passenger 5.0.24.

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-mainline-pagespeed.spec
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-pagespeed.spec
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-mainline-pagespeed.sh
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-pagespeed.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Multiple RPM updates.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updating to nginx mainline 1.9.11

- ulyaoth-nginx/build-ulyaoth-nginx-mainline.sh
> Updated build.

- ulyaoth-nginx/SOURCES/nginx-mainline.conf
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
- ulyaoth-nginx/build-ulyaoth-nginx-mainline.sh
> More dynamic modules

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
- ulyaoth-hiawatha/build-ulyaoth-hiawatha.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updating to Hiawatha 10.1

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
- ulyaoth-tomcat/build-ulyaoth-tomcat8.sh
- ulyaoth-tomcat/build-ulyaoth-tomcat9.sh
> Updating to latest Tomcat 8 and 9.

- ulyaoth-hhvm/README.md
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-lts-3.12.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> HHVM 3.12 (LTS) rpm

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.4.1.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updating to Logstash 2.2.1.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6.spec
- ulyaoth-tomcat/build-ulyaoth-tomcat6.sh
> Updating Tomcat 6 to 6.0.45.

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.4.spec
> Updating to Zookeeper 3.4.8.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Update to Logstash 2.2.2

- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
> Updated to Passenger 5.0.26.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-lts-3.12.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated to HHVM 3.12.1

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-lts-3.9.spec
> Updated to HHVM 3.9.2.

- ulyaoth-banana/SPECS/ulyaoth-banana.spec
- ulyaoth-banana/build-ulyaoth-banana.sh
> Updated to Banana 1.6.0

- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-mainline-pagespeed.spec
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-pagespeed.spec
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-mainline-pagespeed.sh
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-pagespeed.sh
> Updated Pagespeed to 1.10.33.6

- ulyaoth-tomcat-multi/SOURCES/tomcat-multi
#391 reported by Mikael Finhborg.
> fixed wrong exit.

- ulyaoth-tomcat-multi/SPECS/ulyaoth-tomcat-multi.spec
> fixed spec file

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomcat 9.0.0M4

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Fixed files.

- ulyaoth-banana/build-ulyaoth-banana.sh
> Fixing build

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> removed "make rehash, update to beta 1"

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Fix build.

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Fix files.

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
- ulyaoth-wolfssl/build-ulyaoth-wolfssl.sh
> Fixed build with correct directories.

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> configure fix

- ulyaoth-clamav/README
- ulyaoth-clamav/SPECS/ulyaoth-clamav.spec
- ulyaoth-clamav/build-ulyaoth-clamav.sh
> start of clamav rpm

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.4.2

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updating to Tomcat 8.0.33.

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updating to beats 1.1.2.

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updated beats packages to version 1.2.0.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated ot nginx mainline 1.9.13

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Small build fixes

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> removed perl module

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.5.0.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updating Logstash to 2.3.0.

- ulyaoth-logstash/build-ulyaoth-logstash.sh
This build could be faster, please consider using the Gradle Daemon:
https://docs.gradle.org/2.8/userguide/gradle_daemon.html
> Improved build, see description.

- ulyaoth-logstash/build-ulyaoth-logstash.sh
#429
This build could be faster, please consider using the Gradle Daemon:
https://docs.gradle.org/2.8/userguide/gradle_daemon.html
> Fix to build.

- ulyaoth/build-ulyaoth.sh
> Build a source package also.

- ulyaoth-kafka/build-ulyaoth-kafka9-scala2.11.sh
> Fix build file.

- ulyaoth-kafka/SOURCES/kafka
- ulyaoth-kafka/SOURCES/kafka-zookeeper
- ulyaoth-kafka/SOURCES/kafka-zookeeper.init
- ulyaoth-kafka/SOURCES/kafka-zookeeper.service
- ulyaoth-kafka/SPECS/ulyaoth-kafka9-scala2.11.spec
> missed the zookeeper bits.

- ulyaoth-kafka/SPECS/ulyaoth-kafka9-scala2.10.spec
- ulyaoth-kafka/build-ulyaoth-kafka9-scala2.10.sh
> Fixes and scala 2.10 version.

- ulyaoth-kafka/SPECS/ulyaoth-kafka8-scala2.10.spec
- ulyaoth-kafka/build-ulyaoth-kafka8-scala2.10.sh
- ulyaoth-kafka/build-ulyaoth-kafka8-scala2.11.sh
- ulyaoth-kafka/build-ulyaoth-kafka8-scala2.9.1.sh
- ulyaoth-kafka/build-ulyaoth-kafka8-scala2.9.2.sh
> Kafka 8 start

- ulyaoth-kafka/SPECS/ulyaoth-kafka8-scala2.11.spec
> kafka8 with scala 2.11

- ulyaoth-kafka/SPECS/ulyaoth-kafka8-scala2.9.2.spec
> Kafka 8 with Scala 2.9.2

- ulyaoth-kafka/SPECS/ulyaoth-kafka8-scala2.9.1.spec
> Kafka 8 with scala 2.9.1

- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-mainline-pagespeed.spec
- ulyaoth-nginx-pagespeed/SPECS/ulyaoth-nginx-pagespeed.spec
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-mainline-pagespeed.sh
- ulyaoth-nginx-pagespeed/build-ulyaoth-nginx-pagespeed.sh
> Updated to Pagespeed v1.11.33.0-beta

- ulyaoth-vegeta/README
- ulyaoth-vegeta/SPECS/ulyaoth-vegeta.spec
- ulyaoth-vegeta/build-ulyaoth-vegeta.sh
> Initial release of Vegeta rpms.

- ulyaoth-vegeta/build-ulyaoth-vegeta.sh
> change to build.

- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
> Updated Passenger to 5.0.27.

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updated Beats packages to 1.2.1

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
- ulyaoth-tomcat/build-ulyaoth-tomcat7.sh
> Updating Tomcat 7 to 7.0.68.

- ulyaoth-libfuse/README
- ulyaoth-libfuse/SPECS/ulyaoth-libfuse.spec
- ulyaoth-libfuse/build-ulyaoth-libfuse.sh
- ulyaoth-rpm-build.sh
> libfuse rpm

- ulyaoth-libfuse/SPECS/ulyaoth-libfuse.spec
> Added download version.

- ulyaoth-fuse/SPECS/ulyaoth-fuse.spec
- ulyaoth-rpm-build.sh
- ulyaoth-s3fs/README
- ulyaoth-s3fs/SPECS/ulyaoth-s3fs.spec
- ulyaoth-s3fs/build-ulyaoth-s3fs.sh
> Creating s3fs rpms

- ulyaoth-fuse-s3fs/README
- ulyaoth-fuse-s3fs/SPECS/ulyaoth-fuse-s3fs.spec
- ulyaoth-fuse-s3fs/build-ulyaoth-fuse-s3fs.sh
- ulyaoth-rpm-build.sh
- ulyaoth-s3fs/README
> Renamed to fuse-s3fs.

- ulyaoth-fuse-s3fs/build-ulyaoth-fuse-s3fs.sh
> change to build script.

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updating to Go 1.6.1.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updating to Logstash 2.3.1

- ulyaoth-solr/README
- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Added Solr 6 rpms.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
- ulyaoth-nginx/build-ulyaoth-nginx-mainline.sh
> Updating Nginx Mainline 1.9.14.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.13.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updating to HHVM 3.13.1

- ulyaoth/SOURCES/ulyaoth-amazonlinux.repo
- ulyaoth/SOURCES/ulyaoth-centos.repo
- ulyaoth/SOURCES/ulyaoth-fedora.repo
- ulyaoth/SOURCES/ulyaoth-oraclelinux.repo
- ulyaoth/SOURCES/ulyaoth-redhat.repo
- ulyaoth/SOURCES/ulyaoth-scientificlinux.repo
> Changing to "repos.ulyaoth.asia"

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updating to Tomcat 7.0.69

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updating to Go 1.6.2.

- ulyaoth-tomcat-native/SPECS/ulyaoth-tomcat-native1.2.spec
> Updated to Tomcat Native 1.2.6.

- ulyaoth-fuse/SPECS/ulyaoth-fuse.spec
> Updating Fuse to 2.9.6.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated to Nginx Mainline 1.9.15

- ulyaoth-nginx/SOURCES/nginx-mainline.init
- ulyaoth-nginx/SOURCES/nginx.suse-mainline.init
- ulyaoth-nginx/SOURCES/nginx.vh.example_ssl-mainline.conf
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> temp fix for mainline 1.9.15

- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Fix download location

- ulyaoth-nginx/SOURCES/nginx.conf
- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
- ulyaoth-nginx/build-ulyaoth-nginx.sh
> Multiple fixes.

- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Forced build requirements for amazonlinux.

- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
> Removed "jetty-https-ssl.xml".

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updating to OpenSSL 1.1.0 Beta 2.

- ulyaoth/build-ulyaoth.sh
> added noarch

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updating Beats packages to 1.2.2.

- ulyaoth-fuse-s3fs/SPECS/ulyaoth-fuse-s3fs.spec
- ulyaoth-fuse-s3fs/build-ulyaoth-fuse-s3fs.sh
> Recompiled with Fuse 2.9.6.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updating to Logstash 2.3.2.

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
> Updated OpenSSL to 1.0.1t and 1.0.2h.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Updating to Hiawatha 10.2.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
- ulyaoth-hiawatha/build-ulyaoth-hiawatha.sh
> Adding Hiawatha Letsencrypt.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
> fixed hiawatha letsencrypt build.

- ulyaoth-hiawatha/README
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
> small fix.

- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-mainline-passenger5.spec
- ulyaoth-nginx-passenger/SPECS/ulyaoth-nginx-passenger5.spec
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-mainline-passenger5.sh
- ulyaoth-nginx-passenger/build-ulyaoth-nginx-passenger5.sh
> Updating to Passenger 5.0.28.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updating Redis to 3.2.0.

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updating Solr 5 to 5.5.1

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Added: redis-check-rdb

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updating Tomcat 9 to 9.0.0.M6

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updated Tomcat 8 to 8.0.35.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated Kibana 4 to 4.5.1.

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updated Beats to 1.2.3.

- ulyaoth-banana/SPECS/ulyaoth-banana.spec
- ulyaoth-banana/build-ulyaoth-banana.sh
> Updated to Banana 1.6.8.

- ulyaoth-banana/build-ulyaoth-banana.sh
> temp build fix.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updating to Nginx Mainline 1.11.0.

- ulyaoth-fuse-s3fs/SPECS/ulyaoth-fuse-s3fs.spec
> Updated to fuse-s3fs 1.80.

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated Solr 6 to 6.0.1.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Updated Nginx and Nginx Mainline.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.13.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.9.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updating HHVM rpms.

- ulyaoth-hhvm/README.md
> Updating Readme.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.11.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.13.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.3.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.6.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.9.spec
- ulyaoth-rpm-build.sh
> Automating HHVM build.

- ulyaoth-monkey/SPECS/ulyaoth-monkey.spec
> Updated to 1.6.9.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Updated to Hiawatha 10.3.

- ulyaoth-terraform/README
- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> initial release.

- ulyaoth-rpm-build.sh
> added terraform

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
> specify rc1

- ulyaoth-httping/SPECS/ulyaoth-httping.spec
> fixes to files.

- ulyaoth-httping/SPECS/ulyaoth-httping.spec
> missed .gz extension on man files.

- ulyaoth-httping/SPECS/ulyaoth-httping.spec
> fix banner

- ulyaoth-smtpping/README
- ulyaoth-smtpping/SPECS/ulyaoth-smtpping.spec
- ulyaoth-smtpping/build-ulyaoth-smtpping.sh
> initial release

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.14.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated to HHVM 3.14.0.

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
> forgot $RPM_BUILD_ROOT

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
> missed files.

- ulyaoth-kafka/SPECS/ulyaoth-kafka-scala2.8.0.spec
> updated source0

- ulyaoth-hhvm/README.md
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.14.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated to 3.14.1

- ulyaoth-httpdiff/SPECS/ulyaoth-httpdiff.spec
- ulyaoth-httpdiff/build-ulyaoth-httpdiff.sh
> Updated to latest master build.

- ulyaoth-httpdiff/README
> updated readme.

- ulyaoth-httpdiff/build-ulyaoth-httpdiff.sh
> fix to build

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> updated to Terraform 0.7.0-rc2.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomcat 9.0.0.M8.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updated to Tomcat 8.0.36.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Creating Tomcat 8.5 rpms.

- ulyaoth-rpm-build.sh
- ulyaoth-tomcat/README
- ulyaoth-tomcat/build-ulyaoth-tomcat8.5.sh
> atomcat 8.5

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updated to Logstash 2.3.3.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updating Redis to 3.2.1.

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated to Solr 6.1.0.

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated to WolfSSL 3.9.6.

- ulyaoth-nginx-modules/README
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-or-mainline-modules.sh
> adding headers-more-module.

- ulyaoth-nginx-modules/README
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-pam-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-or-mainline-modules.sh
> added pam module.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-pam-module.spec
> fix to pam module.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-or-mainline-modules.sh
> adding required devel-kit

- ulyaoth-nginx-modules/README
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
> adding devel-kit

- ulyaoth-nginx-modules/README
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-encrypted-session-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-or-mainline-modules.sh
> added encrypted session

- ulyaoth-nginx-modules/README
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-or-mainline-modules.sh
> array var module

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated to 7.0.70.

- ulyaoth-fuse/SPECS/ulyaoth-fuse.spec
> Updated to Fuse 2.9.7.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-and-mainline-modules.sh
> Naxsi module.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> fixed module

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> added: /naxsi_src

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> added obsolete

- ulyaoth-nginx-modules/SOURCES/nbs.rules
- ulyaoth-nginx-modules/SOURCES/nginx.conf-naxsiexample
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> adding naxsi files.

- ulyaoth-fuse-s3fs/SPECS/ulyaoth-fuse-s3fs.spec
> fuse-s3fs recompiled with Fuse 2.9.7.

- ulyaoth-leveldb/README
- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
- ulyaoth-leveldb/build-ulyaoth-leveldb.sh
> Leveldb 1.18 initial release.

- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
> adding license file.

- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
> added documentation

- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
- ulyaoth-leveldb/build-ulyaoth-leveldb.sh
- ulyaoth-rpm-build.sh
> fixing leveldb

- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
> fixed wrong include.

- ulyaoth-rpm-build.sh
- ulyaoth-tmux/README
- ulyaoth-tmux/SPECS/ulyaoth-tmux.spec
- ulyaoth-tmux/build-ulyaoth-tmux.sh
> tmux initial release

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updated to Solr 5.5.2.

- ulyaoth-mbedtls/README
- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls2.3.spec
- ulyaoth-mbedtls/build-ulyaoth-mbedtls2.3.sh
- ulyaoth-rpm-build.sh
> Creating mbedTLS 2.3 rpms.

- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls.spec
- ulyaoth-mbedtls/SPECS/ulyaoth-mbedtls2.1.spec
> Updated to latest version.

- ulyaoth-monkey/SPECS/ulyaoth-monkey.spec
> Updated mbedTLS to 2.3.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Recompiled with mbedTLS 2.3.

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.14.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.9.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated to latest versions.

- ulyaoth-tomcat-native/SPECS/ulyaoth-tomcat-native1.2.spec
> Updated to version 1.2.8.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.5.2.

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated to 1.11.2.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
> Updated to 2.3.4.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updating to M9.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated to 8.5.4.

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> Updated to 1.3.1.6

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updated to go 1.6.3.

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.5.spec
> Updated to Zookeeper 3.5.2.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updated Redis to 3.2.2.

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Update Terraform to 0.7.0-rc4

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated WolfSSL to 3.9.8

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> unclosed macro or bad line continuation

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Missed GeoIP files.

- ulyaoth-kafka/README
- ulyaoth-kafka/SOURCES/kafka-sysconfig-initd
- ulyaoth-kafka/SOURCES/kafka-sysconfig-systemd
- ulyaoth-kafka/SOURCES/kafka-zookeeper-sysconfig-initd
- ulyaoth-kafka/SOURCES/kafka-zookeeper-sysconfig-systemd
- ulyaoth-kafka/SOURCES/kafka-zookeeper.init
- ulyaoth-kafka/SOURCES/kafka-zookeeper.service
- ulyaoth-kafka/SOURCES/kafka.init
- ulyaoth-kafka/SOURCES/kafka.service
- ulyaoth-kafka/SPECS/ulyaoth-kafka-scala2.8.0.spec
- ulyaoth-kafka/build-ulyaoth-kafka-scala2.8.0.sh
> added first release

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to 0.7.0.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updated to Redis 3.2.3.

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updated to OpenSSL 1.1.0 Beta 3.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.5.4

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.9.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated HHVM to latest available.

- ulyaoth-leveldb/SPECS/ulyaoth-leveldb.spec
> Updated to 1.19.

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated Terraform to 0.7.1

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updated Go to 1.7

- ulyaoth-hhvm/README.md
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.14.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.9.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated HHVM to latest version.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-and-mainline-modules.sh
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Recompiled with nginx 1.11.3 and updated version.

- ulyaoth-vegeta/SPECS/ulyaoth-vegeta.spec
- ulyaoth-vegeta/build-ulyaoth-vegeta.sh
> Updated to 6.1.1

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to Terraform 0.7.2

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated Solr 6 to 6.2.0

- ulyaoth-httpdiff/SPECS/ulyaoth-httpdiff.spec
> Updated to official 1.0.0 release

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updated to OpenSSL 1.1.0 release.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.6.0.

- ulyaoth-logstash/SPECS/ulyaoth-logstash.spec
- ulyaoth-logstash/build-ulyaoth-logstash.sh
> Updated to Logstash 2.4.0

- ulyaoth-filebeat/SPECS/ulyaoth-filebeat.spec
- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/SPECS/ulyaoth-packetbeat.spec
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/SPECS/ulyaoth-topbeat.spec
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Updated to Beats 1.3.0.

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Fix to download url

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> fix to extract

- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
> Fix compile with go

- ulyaoth-filebeat/build-ulyaoth-filebeat.sh
- ulyaoth-packetbeat/build-ulyaoth-packetbeat.sh
- ulyaoth-topbeat/build-ulyaoth-topbeat.sh
> Fix compile with Go.

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.4.spec
> Updated to Zookeeper 3.4.9

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated to Tomcat 8.5.5

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomcat 9.0.0.M10

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updated to Tomcat 8.0.37

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to Terraform 0.7.3

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updated to Go 1.7.1

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.15.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Creating HHVM 3.15 (LTS) rpms

- ulyaoth-beats/SPECS/ulyaoth-beats.spec
> Fixed buildrequires for packetbeat

- ulyaoth-beats/build-ulyaoth-beats.sh
> added builddep

- ulyaoth-kibana/SPECS/ulyaoth-kibana4.spec
> Updated to Kibana 4.6.1

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated Nginx Mainline 1.11.4

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> Updated to Kafka Manager 1.3.1.8

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updated Solr 5 to 5.5.3

- ulyaoth-beats/SPECS/ulyaoth-beats.spec
- ulyaoth-beats/build-ulyaoth-beats.sh
> Updated Beats to 1.3.1.

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
> Updated to OpenSSL 1.0.1u

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updated to OpenSSL 1.1.0b

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated WolfSSL to 3.9.10

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Fixed prep

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated to Tomcat 7.0.72

- ulyaoth-tmux/SPECS/ulyaoth-tmux.spec
> Updated to tmux 2.3.

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated Terraform to 0.7.4.

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated to Solr 6.2.1

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updated to Redis 3.2.4

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
> Updated to Solr 5.5.3

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-and-mainline-modules.sh
> Updated Naxsi to 0.55.1.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> Updated to Naxsi 0.55.1

- ulyaoth-openssl/SOURCES/ulyaoth-openssl0.9.8.conf
- ulyaoth-openssl/SOURCES/ulyaoth-openssl1.0.0.conf
- ulyaoth-openssl/SOURCES/ulyaoth-openssl1.0.1.conf
- ulyaoth-openssl/SOURCES/ulyaoth-openssl1.0.2.conf
- ulyaoth-openssl/SOURCES/ulyaoth-openssl1.1.0.conf
- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Adding ldd fix

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> added -p /sbin/ldconfig

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> changed to /usr/sbin/ldconfig

- ulyaoth-haproxy/README
- ulyaoth-haproxy/SOURCES/haproxy.cfg
- ulyaoth-haproxy/SOURCES/haproxy.init
- ulyaoth-haproxy/SOURCES/haproxy.service
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
- ulyaoth-haproxy/build-ulyaoth-haproxy1.6.sh
> start of haproxy

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> updated if statement

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> added DESTDIR=$RPM_BUILD_ROOT

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> added small fixes.

- ulyaoth-haproxy/build-ulyaoth-haproxy1.6.sh
> Fix build script.

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.3.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.4.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.5.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> Multiple fixes

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.3.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.4.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.5.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> More fixes!

- ulyaoth-haproxy/SOURCES/haproxy1.3.init
- ulyaoth-haproxy/SOURCES/haproxy1.3.service
- ulyaoth-haproxy/SOURCES/haproxy1.4.init
- ulyaoth-haproxy/SOURCES/haproxy1.4.service
- ulyaoth-haproxy/SOURCES/haproxy1.5.init
- ulyaoth-haproxy/SOURCES/haproxy1.5.service
- ulyaoth-haproxy/SOURCES/haproxy1.6.init
- ulyaoth-haproxy/SOURCES/haproxy1.6.service
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.3.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.4.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.5.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> More fixes to seperate versions.

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.3.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.4.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.5.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> Fix config dir

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated Tomcat 9 to 9.0.0.M11

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated Tomcat 8.5 to 8.5.6

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updated Tomcat 8 to 8.0.38

- ulyaoth-tomcat-native/SPECS/ulyaoth-tomcat-native1.2.spec
- ulyaoth-tomcat-native/build-ulyaoth-tomcat-native1.2.sh
> Updated to Tomcat Native 1.2 version 1.2.10

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to Terraform 0.7.6

- ulyaoth-httping/SPECS/ulyaoth-httping.spec
> Updated to httping 2.5

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Updated to Hiawatha 10.4

- ulyaoth-banana/SPECS/ulyaoth-banana.spec
- ulyaoth-banana/build-ulyaoth-banana.sh
> Updated to Banana 1.6.12

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated to Nginx Mainline 1.11.5

- ulyaoth-banana/build-ulyaoth-banana.sh
https://github.com/lucidworks/banana/issues/276
> 1.6.12 still missing build files.

- ulyaoth-varnish/SPECS/ulyaoth-varnish5.spec
> fixed name to initrc

- ulyaoth-varnish/SOURCES/varnish-limits.conf
- ulyaoth-varnish/SPECS/ulyaoth-varnish5.spec
> added limits file.

- ulyaoth-lua/README
- ulyaoth-lua/SOURCES/ulyaoth-lua5.3.conf
- ulyaoth-lua/SPECS/ulyaoth-lua5.3.spec
- ulyaoth-lua/build-ulyaoth-lua5.3.sh
> Lua 5.3 initial release

- ulyaoth-lua/SPECS/ulyaoth-lua5.3.spec
> Removed distribution specific

- ulyaoth-lua/SPECS/ulyaoth-lua5.3.spec
> small build fix

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
> Added Lua support.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-pam-module.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Updated to Nginx 1.10.2

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updated Redis to 3.2.5

- ulyaoth-kibana/SPECS/ulyaoth-kibana5.spec
- ulyaoth-kibana/build-ulyaoth-kibana5.sh
- ulyaoth-rpm-build.sh
> Added Kibana 5

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to 0.7.9

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-and-mainline-modules.sh
> Updated Headers more to 0.32

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated to Tomcat 8.5.8.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomcat 9.0.0.M13

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated to Solr 6.3.0.

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updated to OpenSSL 1.1.0c

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-passenger5-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-stable-and-mainline-modules.sh
> adding passenger5 module.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-passenger5-module.spec
> added requires.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-passenger5-module.spec
> fix mistake and update nginx

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated to 3.9.10b

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated to Tomcat 7.0.73

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6.spec
> Updated to Tomcat 6.0.48

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated to Nginx Mainline 1.11.6

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-passenger5-module.spec
- ulyaoth-nginx-modules/build-ulyaoth-nginx-passenger5-modules.sh
> fix build, to git clone.

- ulyaoth-haproxy/SOURCES/haproxy1.7.cfg
- ulyaoth-haproxy/SOURCES/haproxy1.7.init
- ulyaoth-haproxy/SOURCES/haproxy1.7.service
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.7.spec
- ulyaoth-haproxy/build-ulyaoth-haproxy1.7.sh
> Adding HAProxy 1.7

- ulyaoth-geoipupdate/README
- ulyaoth-geoipupdate/SPECS/ulyaoth-geoipupdate.spec
- ulyaoth-geoipupdate/build-ulyaoth-geoipupdate.sh
> Initial release for geoipupdate

- ulyaoth-lua/SPECS/ulyaoth-lua5.3.spec
> Updated Lua to 5.3.4

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updated to Go 1.7.5

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated to WolfSSL 3.10.0a

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomat 9.0.0.M17

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Update Tomcat 8 to 8.0.41

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Update Tomcat 8.5 to 8.5.11

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> 7 to 7.0.75

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Updated to Redis 3.2.8

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Update Terraform to 0.8.6

- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.12.spec
- ulyaoth-hhvm/SPECS/ulyaoth-hhvm-3.15.spec
- ulyaoth-hhvm/build-ulyaoth-hhvm.sh
> Updated HHVM

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Update Hiawatha to 10.5

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Update Solr 6 to 6.4.0.

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Update Go to 1.8.0.

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
- ulyaoth-solr/build-ulyaoth-solr5.sh
> Updated Solr 5 to 5.5.4

- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> Updated to OpenSSL 1.1.0e

- ulyaoth-screen/SPECS/ulyaoth-screen.spec
> Update Screen to 4.5.0.

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated WolfSSL to 3.10.3.

- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
> Fixed summary

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated to Solr 6 version 6.4.1

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> Update Kafka Manager to 1.3.3.0

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated Solr 6 to 6.4.2.

- ulyaoth-vegeta/SPECS/ulyaoth-vegeta.spec
- ulyaoth-vegeta/build-ulyaoth-vegeta.sh
> Updated Vegeta to 6.2.0

- ulyaoth-tomcat-native/SPECS/ulyaoth-tomcat-native1.2.spec
> Updated Tomcat Native 1.2 to 1.2.12

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated Terraform to 0.8.8

- ulyaoth-screen/SPECS/ulyaoth-screen.spec
> Updated Screen to 4.5.1

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> Updated Kafka Manager to 1.3.3.1

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.7.spec
> Updated HAProxy 1.7 to 1.7.3

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> updated to 1.3.3.4

- ulyaoth-keepalived/README
- ulyaoth-keepalived/SPEC/ulyaoth-keepalived.spec
- ulyaoth-keepalived/build-ulyaoth-keepalived.sh
> initial upload

- ulyaoth-keepalived/SPEC/ulyaoth-keepalived.spec
> fixed spec file.

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated Terraform to 0.9.0.

- ulyaoth/SOURCES/ulyaoth-amazonlinux.repo
- ulyaoth/SOURCES/ulyaoth-centos.repo
- ulyaoth/SOURCES/ulyaoth-fedora.repo
- ulyaoth/SOURCES/ulyaoth-oraclelinux.repo
- ulyaoth/SOURCES/ulyaoth-redhat.repo
- ulyaoth/SOURCES/ulyaoth-scientificlinux.repo
- ulyaoth/SPECS/ulyaoth.spec
> changed domain to repos.ulyaoth.io.

- ulyaoth-hitch/README
- ulyaoth-hitch/SOURCES/hitch.conf
- ulyaoth-hitch/SOURCES/hitch.init
- ulyaoth-hitch/SOURCES/hitch.service
- ulyaoth-hitch/SPECS/ulyaoth-hitch.spec
- ulyaoth-hitch/build-ulyaoth-hitch.sh
> Initial release for Hitch

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
> removed unused files from older openssl version.

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
> Fixed file names.

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
> cleaning files.

- ulyaoth-openssl/SPECS/ulyaoth-openssl0.9.8.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.0.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.1.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec
- ulyaoth-openssl/SPECS/ulyaoth-openssl1.1.0.spec
> [openssl] tag doc files

- ulyaoth-lego/README
- ulyaoth-lego/SPECS/ulyaoth-lego.spec
- ulyaoth-lego/build-ulyaoth-lego.sh
> Initial release lego rpm

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated to wolfSSL 3.10.4

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated Tomcat 7 to t.0.77

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Update Tomcat 8 to 8.0.43

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated Tomcat 8.5 to 8.5.13

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated Tomcat 9 to 9.0.0.M19

- ulyaoth-go/SPECS/ulyaoth-go.spec
> Updated Go to 1.8.1

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.4.spec
> Updating Zookeer 3.4 to 3.4.10

- ulyaoth-vegeta/SPECS/ulyaoth-vegeta.spec
- ulyaoth-vegeta/build-ulyaoth-vegeta.sh
> Updated Vegeta to 6.3.0

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated Terraform to 0.9.2

- ulyaoth-keepalived/SPEC/ulyaoth-keepalived.spec
> Updating Keepalived to 1.3.5

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated Solr 6 to 6.5.0.

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.7.spec
- ulyaoth-haproxy/build-ulyaoth-haproxy1.7.sh
> Updated HAProxy 1.7 to 1.7.4

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
- ulyaoth-haproxy/build-ulyaoth-haproxy1.6.sh
> Updated HAProxy 1.6 to 1.6.12

- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.6.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.7.spec
- ulyaoth-lua/SOURCES/ulyaoth-lua5.3.conf
- ulyaoth-lua/SPECS/ulyaoth-lua5.3.spec
- ulyaoth-lua/build-ulyaoth-lua5.3.sh
> changes to lua rpm.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6.spec
> Update tomcat 6 to 6.0.53

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> updated to Terraform 0.9.3.

- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha-letsencrypt.spec
- ulyaoth-hiawatha/SPECS/ulyaoth-hiawatha.spec
> Updated Hiawatha to 10.6.

- ulyaoth-tmux/SPECS/ulyaoth-tmux.spec
> Updated Tmux to 2.4

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated Tomcat 9 to 9.0.0.M20

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated Tomcat 8.5 to 8.5.14

- ulyaoth-varnish/SPECS/ulyaoth-varnish5.1.spec
> Updated Varnish 5.1 to 5.1.1.

- ulyaoth-emojify/README
- ulyaoth-emojify/SPECS/ulyaoth-emojify.spec
- ulyaoth-emojify/build-ulyaoth-emojify.sh
> initial release for emojify

- ulyaoth-varnish/SPECS/ulyaoth-varnish5.1.spec
> Updated Varnish 5.1 to 5.1.2

- ulyaoth-emojify/SPECS/ulyaoth-emojify.spec
> Fixed build

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.5.spec
> Updated Zookeeper to 3.5.3-beta.

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-encrypted-session-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-pam-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated to Nginx Mainline 1.11.13 & Njs 0.1.10

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
- ulyaoth-varnish/SPECS/ulyaoth-varnish4.1.spec
> Multiple updates

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> updated wolfSSL to 3.11.0

- ulyaoth-luajit/SPECS/ulyaoth-luajit.spec
> Updated LuaJIT to 2.0.5

- ulyaoth-emojify/SPECS/ulyaoth-emojify.spec
> Updated Emojify to 2.0.0.

- ulyaoth-varnish/SPECS/ulyaoth-varnish4.1.spec
> Updated to Varnish 4.1.7

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated to Tomcat 9.0.0.M22

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> Updated Tomcat 8.5 to 8.5.16

- ulyaoth-screen/SPECS/ulyaoth-screen.spec
> Updated to Screen 4.6.0

- ulyaoth-apr/SPECS/ulyaoth-apr.spec
- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to 1.6.2

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-ulyaoth-solr6.sh
> Updated to 6.6.0

- ulyaoth-banana/SPECS/ulyaoth-banana.spec
- ulyaoth-banana/build-ulyaoth-banana.sh
> updated to 1.6.17

- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
> Updated to Terraform 0.9.11

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Updated to Tomcat 8.0.45.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated Tomcat 7 to 7.0.79

- ulyaoth-kafka-manager/SPECS/ulyaoth-kafka-manager.spec
- ulyaoth-kafka-manager/build-ulyaoth-kafka-manager.sh
> Updated to 1.3.3.7

- ulyaoth-cmake/SPECS/ulyaoth-cmake.spec
- ulyaoth-haproxy/SPECS/ulyaoth-haproxy1.7.spec
- ulyaoth-parallel/SPECS/ulyaoth-parallel.spec
- ulyaoth-redis/SPECS/ulyaoth-redis3.spec
- ulyaoth-screen/SPECS/ulyaoth-screen.spec
- ulyaoth-terraform/SPECS/ulyaoth-terraform.spec
- ulyaoth-terraform/build-ulyaoth-terraform.sh
- ulyaoth-varnish/SPECS/ulyaoth-varnish4.1.spec
- ulyaoth-varnish/SPECS/ulyaoth-varnish5.1.spec
#1494 #1493 #1492  #1491 #1490 #1481 #1480
> Updated to latest version

- ulyaoth-tengine/SPECS/ulyaoth-tengine.spec
> Updated Tegine to 2.2.1

- ulyaoth-parallel/SPECS/ulyaoth-parallel.spec
> Updated parallel to 20171022

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-lua-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-lua-module.spec
- ulyaoth-nginx-modules/build-lua.sh
> lua module

- ulyaoth-solr/SPECS/ulyaoth-solr7-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr7-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr7.spec
- ulyaoth-solr/build-solr7.sh
> Updated solr 7 to 7.2.1

- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.4.spec
- ulyaoth-zookeeper/SPECS/ulyaoth-zookeeper3.5.spec
> Updated Zookeeper

- ulyaoth-varnish/SPECS/ulyaoth-varnish4.1.spec
> Updated Varnish

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/SPECS/ulyaoth-solr7-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr7-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr7.spec
- ulyaoth-solr/build-solr6.sh
- ulyaoth-solr/build-solr7.sh
> updated solr

- ulyaoth-wolfssl/SPECS/ulyaoth-wolfssl.spec
> Updated WolfSSL

- ulyaoth-redis/SPECS/ulyaoth-redis4.spec
> Updated Redis

- ulyaoth-parallel/SPECS/ulyaoth-parallel.spec
> Updated Parallel

- ulyaoth-keepalived/SPECS/ulyaoth-keepalived.spec
> updated keepalived

- ulyaoth-iperf/SPECS/ulyaoth-iperf3.spec
> updated iperf

- ulyaoth/SOURCES/ulyaoth-amazonlinux.repo
- ulyaoth/SOURCES/ulyaoth-amazonlinux2.repo
- ulyaoth/SOURCES/ulyaoth-centos.repo
- ulyaoth/SOURCES/ulyaoth-fedora.repo
- ulyaoth/SOURCES/ulyaoth-oraclelinux.repo
- ulyaoth/SOURCES/ulyaoth-redhat.repo
- ulyaoth/SOURCES/ulyaoth-scientificlinux.repo
- ulyaoth/SPECS/ulyaoth.spec
- ulyaoth/build-ulyaoth.sh
> Fixed repo files

- ulyaoth/SOURCES/ulyaoth-amazonlinux.repo
- ulyaoth/SOURCES/ulyaoth-amazonlinux2.repo
- ulyaoth/SOURCES/ulyaoth-centos.repo
- ulyaoth/SOURCES/ulyaoth-fedora.repo
- ulyaoth/SOURCES/ulyaoth-oraclelinux.repo
- ulyaoth/SOURCES/ulyaoth-redhat.repo
- ulyaoth/SOURCES/ulyaoth-scientificlinux.repo
- ulyaoth/SPECS/ulyaoth.spec
> from tabs to spaces

- ulyaoth-keepalived/SPECS/ulyaoth-keepalived.spec
> Updated to 1.4.5

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
- ulyaoth-nginx-modules/build-naxsi.sh
> Updated to 0.56.

- ulyaoth/SPECS/ulyaoth.spec
- ulyaoth/build-ulyaoth.sh
> multiple changes

- ulyaoth/SPECS/ulyaoth.spec
> Fixed so the repo file is not a config.

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat9.spec
> Updated Tomcat 9

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.5.spec
> update tomcat 8.5

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat8.spec
> Build fix Tomcat 8

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat7.spec
> Updated Tomcat 7

- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-admin.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-docs.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6-examples.spec
- ulyaoth-tomcat/SPECS/ulyaoth-tomcat6.spec
> Tomcat 6 spec file minor changes

- ulyaoth-solr/README
- ulyaoth-solr/SPECS/ulyaoth-solr8-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr8-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr8.spec
- ulyaoth-solr/build-solr8.sh
> Created Solr 8

- ulyaoth-solr/SPECS/ulyaoth-solr6-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr6.spec
- ulyaoth-solr/build-solr6.sh
> Updated solr 6

- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
> Small update

- ulyaoth-solr/SPECS/ulyaoth-solr4.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-docs.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5-examples.spec
- ulyaoth-solr/SPECS/ulyaoth-solr5.spec
> minor change to email

- ulyaoth-nginx/SPECS/ulyaoth-nginx-mainline.spec
> Updated nginx mainline

- ulyaoth-nginx/SPECS/ulyaoth-nginx.spec
> Updated nginx

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-array-var-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-array-var-module.spec
> array var recompile

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-devel-kit-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-devel-kit-module.spec
> recompiled devel-kit

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-echo-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-echo-module.spec
> Recompiled echo

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-form-input-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-form-input-module.spec
> Recompiled form-input

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-headers-more-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-headers-more-module.spec
> recompiled headers more

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-naxsi-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-naxsi-module.spec
> Recompiled naxsi

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-njs-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-njs-module.spec
> updated njs

- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-mainline-passenger5-module.spec
- ulyaoth-nginx-modules/SPECS/ulyaoth-nginx-passenger5-module.spec
> Updated Passenger 5
